p8105\_hw3\_yz4186
================
Yunxi Zhang
10/18/2021

# Homework 3

### Problem 1

#### This problem uses the Instacart data. DO NOT include this dataset in your local data directory; instead, load the data from the p8105.datasets using: library(p8105.datasets) data(“instacart”)

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
## load the dataset
library(p8105.datasets)
data("instacart")
```

#### a) The goal is to do some exploration of this dataset. To that end, write a short description of the dataset, noting the size and structure of the data, describing some key variables, and giving illstrative examples of observations. Then, do or answer the following (commenting on the results of each):

``` r
instacart ## take a look at the data
```

    ## # A tibble: 1,384,617 × 15
    ##    order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##       <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ##  1        1      49302                 1         1  112108 train               4
    ##  2        1      11109                 2         1  112108 train               4
    ##  3        1      10246                 3         0  112108 train               4
    ##  4        1      49683                 4         0  112108 train               4
    ##  5        1      43633                 5         1  112108 train               4
    ##  6        1      13176                 6         0  112108 train               4
    ##  7        1      47209                 7         0  112108 train               4
    ##  8        1      22035                 8         1  112108 train               4
    ##  9       36      39612                 1         0   79431 train              23
    ## 10       36      19660                 2         1   79431 train              23
    ## # … with 1,384,607 more rows, and 8 more variables: order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>, product_name <chr>,
    ## #   aisle_id <int>, department_id <int>, aisle <chr>, department <chr>

The “instacart” dataset has 1384617 rows and 15 columns. It contains
data of each order with showing the “product id”, “user id” and “product
name” and other detailder information.

#### b) How many aisles are there, and which aisles are the most items ordered from?

``` r
 instacart_df = 
  instacart %>% 
  group_by(aisle) %>% 
  summarize(n_order = n()) %>% 
  arrange(desc(n_order)) #arrange(desc(n_order)) ## rank the number of order of each aisle

instacart_df
```

    ## # A tibble: 134 × 2
    ##    aisle                         n_order
    ##    <chr>                           <int>
    ##  1 fresh vegetables               150609
    ##  2 fresh fruits                   150473
    ##  3 packaged vegetables fruits      78493
    ##  4 yogurt                          55240
    ##  5 packaged cheese                 41699
    ##  6 water seltzer sparkling water   36617
    ##  7 milk                            32644
    ##  8 chips pretzels                  31269
    ##  9 soy lactosefree                 26240
    ## 10 bread                           23635
    ## # … with 124 more rows

Thus, there are 134 aisles and “fresh vegetables” is the most ordered
one.

#### c) Make a plot that shows the number of items ordered in each aisle, limiting this to aisles with more than 10000 items ordered. Arrange aisles sensibly, and organize your plot so others can read it.

``` r
instacart_df %>% 
  filter(n_order > 10000) %>% ## limit to aisles with more than 10000
  mutate(
    aisle = factor(aisle), ## convert char var to factor var
    aisle = fct_reorder(aisle, n_order) ## arrange aisles sensibly
  ) %>%
  ggplot(aes(x = aisle, y = n_order)) + 
  geom_point(alpha = .3) +
  labs(
    title = "aisle plot",
    x = "aisle",
    y = "number of items ordered"
   ) + 
theme(axis.text.x = element_text(angle = -45, vjust = 0.5, hjust = 0)) +
  geom_point()
```

![](p8105_hw3_yz4186_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

#### d) Make a table showing the three most popular items in each of the aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”. Include the number of times each item is ordered in your table.

``` r
instacart %>% 
  group_by(aisle) %>% 
  filter(
    aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits") ## filter the aisle
    ) %>% 
  count(product_name) %>%  ## count the times of ordered 
  filter(min_rank(desc(n)) < 4) %>%  ## filter the top 3 orders
  arrange(desc(n)) %>%    ## arrange them in descending order
  knitr::kable() 
```

| aisle                      | product\_name                                 |    n |
|:---------------------------|:----------------------------------------------|-----:|
| packaged vegetables fruits | Organic Baby Spinach                          | 9784 |
| packaged vegetables fruits | Organic Raspberries                           | 5546 |
| packaged vegetables fruits | Organic Blueberries                           | 4966 |
| baking ingredients         | Light Brown Sugar                             |  499 |
| baking ingredients         | Pure Baking Soda                              |  387 |
| baking ingredients         | Cane Sugar                                    |  336 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |   30 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |   28 |
| dog food care              | Small Dog Biscuits                            |   26 |

#### e) Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7 table).

``` r
 instacart %>% 
  ## select the product
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(
  ## calculate the mean hour of each day
    mean_hour = mean(order_hour_of_day),
  ) %>% 
  pivot_wider(
    names_from = "order_dow",
    values_from = "mean_hour"
  ) %>% 
  knitr::kable() 
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

| product\_name    |        0 |        1 |        2 |        3 |        4 |        5 |        6 |
|:-----------------|---------:|---------:|---------:|---------:|---------:|---------:|---------:|
| Coffee Ice Cream | 13.77419 | 14.31579 | 15.38095 | 15.31818 | 15.21739 | 12.26316 | 13.83333 |
| Pink Lady Apples | 13.44118 | 11.36000 | 11.70213 | 14.25000 | 11.55172 | 12.78431 | 11.93750 |

## Problem 2

#### This problem uses the BRFSS data. DO NOT include this dataset in your local data directory; instead, load the data from the p8105.datasets package.

``` r
library("p8105.datasets")
data("brfss_smart2010")
```

#### a) First, do some data cleaning:

#### format the data to use appropriate variable names;focus on the “Overall Health” topic include only responses from “Excellent” to “Poor” organize; responses as a factor taking levels ordered from “Poor” to “Excellent”;

``` r
brfss_df =
  brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(
    topic == "Overall Health",  ## focus on the "Overall Health" topic
    response %in% c("Excellent", "Very good", "Good", "Fair", "Poor") ## Including only these 4 responses
) %>%
  mutate(
    response = factor(response),
    ## convert char to factor 
    response = fct_relevel(response, c("Poor", "Fair", "Good", "Very good", "Excellent")) 
  )
```

#### b) Using this dataset, do or answer the following (commenting on the results of each):

##### In 2002, which states were observed at 7 or more locations? What about in 2010?

``` r
## In 2002
brfss_df %>% 
  filter(year == "2002") %>%  
  group_by(locationabbr) %>%
  distinct(locationdesc) %>% ## count distinct location in each state
  count() %>%    
  filter( n >= 7) %>% ## filter state with at 7 or more locations
  arrange(n)
```

    ## # A tibble: 6 × 2
    ## # Groups:   locationabbr [6]
    ##   locationabbr     n
    ##   <chr>        <int>
    ## 1 CT               7
    ## 2 FL               7
    ## 3 NC               7
    ## 4 MA               8
    ## 5 NJ               8
    ## 6 PA              10

``` r
## In 2010
brfss_df %>% 
  filter(year == "2010") %>% 
  group_by(locationabbr) %>%  
  distinct(locationdesc) %>%  ## count distinct location in each state
  count() %>%    
  filter( n >= 7) %>%  ## filter state with at 7 or more locations
  arrange(n)
```

    ## # A tibble: 14 × 2
    ## # Groups:   locationabbr [14]
    ##    locationabbr     n
    ##    <chr>        <int>
    ##  1 CO               7
    ##  2 PA               7
    ##  3 SC               7
    ##  4 OH               8
    ##  5 MA               9
    ##  6 NY               9
    ##  7 NE              10
    ##  8 WA              10
    ##  9 CA              12
    ## 10 MD              12
    ## 11 NC              12
    ## 12 TX              16
    ## 13 NJ              19
    ## 14 FL              41

Therefore, “CT”, “FL”, “MA”, “MC”, “NJ” and “PA” have at 7 or more
locations in 2002. “CO”, “PA”,“SC”, “OH”, “MA”, “NY”, “NE”, “WA”, “CA”
and “MD” have at 7 or more locations in 2010.

#### c) Construct a dataset that is limited to Excellent responses, and contains, year, state, and a variable that averages the data\_value across locations within a state. Make a “spaghetti” plot of this average value over time within a state (that is, make a plot showing a line for each state across years – the geom\_line geometry and group aesthetic will help).

``` r
Excellent_df = 
  brfss_df %>% 
  filter(response == "Excellent") %>% 
  select(year, locationabbr, response, data_value) %>% 
  group_by(year,locationabbr) %>% 
  ## Calculate the average value for each state
  summarize(average= mean(data_value)) 
```

    ## `summarise()` has grouped output by 'year'. You can override using the `.groups` argument.

``` r
Excellent_df
```

    ## # A tibble: 443 × 3
    ## # Groups:   year [9]
    ##     year locationabbr average
    ##    <int> <chr>          <dbl>
    ##  1  2002 AK              27.9
    ##  2  2002 AL              18.5
    ##  3  2002 AR              24.1
    ##  4  2002 AZ              24.1
    ##  5  2002 CA              22.7
    ##  6  2002 CO              23.1
    ##  7  2002 CT              29.1
    ##  8  2002 DC              29.3
    ##  9  2002 DE              20.9
    ## 10  2002 FL              25.7
    ## # … with 433 more rows

``` r
## make a plot
Excellent_df %>% 
ggplot(aes(x = year, y = average, color = locationabbr)) +
  geom_line(alpha = 0.5) +
  labs(
    title = "The mean data value over time within state",
    y = "Average value", 
    x = "Year",
  ) +
  viridis::scale_color_viridis(discrete = T) 
```

    ## Warning: Removed 3 row(s) containing missing values (geom_path).

![](p8105_hw3_yz4186_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->

#### d) Make a two-panel plot showing, for the years 2006, and 2010, distribution of data\_value for responses (“Poor” to “Excellent”) among locations in NY State.

``` r
brfss_df %>% 
   filter(
      year %in% c(2006, 2010), ## for years 2006 and 2010
      locationabbr == "NY"  ## in NY State
  ) %>% 
    ggplot(aes(x = data_value, color = year)) +
    geom_density() +  ## generate distribution plot
    facet_grid(. ~ year) + 
    labs(title = "Distribution of data value of responses in 2006 and 2010 in NY    State",
    x = "Data value of responses",
    y = "Density of data value") 
```

![](p8105_hw3_yz4186_files/figure-gfm/unnamed-chunk-10-1.png)<!-- -->

### Problem 3

#### a) Load, tidy, and otherwise wrangle the data. Your final dataset should include all originally observed variables and values; have useful variable names; include a weekday vs weekend variable; and encode data with reasonable variable classes. Describe the resulting dataset (e.g. what variables exist, how many observations, etc).

``` r
## load the data
accel_df = read_csv("./data/accel_data.csv")
```

    ## Rows: 35 Columns: 1443

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr    (1): day
    ## dbl (1442): week, day_id, activity.1, activity.2, activity.3, activity.4, ac...

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
## tidy the data
## change the data to human_read 
accel_weekday =
  accel_df %>% 
  pivot_longer(   
    activity.1 : activity.1440,
    names_to = "minute",
    names_prefix = "activity.",
    values_to = "activity_counts"
  ) %>%
  
## generate weekday vs weekend variable
mutate( 
      weekday = 
         case_when( day %in%    
  c("Monday","Tuesday","Wednesday","Thursday","Friday") ~ "weekday",    day %in% c("Saturday","Sunday") ~ "weekend")
  ) %>% 
  
## reorder the day, weekday and minute variable
mutate(
    day = as.factor(day),
    day = fct_relevel(day, 
      "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" , "Saturday", "Sunday"),
    weekday = as.factor(weekday),
    minute = as.numeric(minute)
    )

accel_weekday
```

    ## # A tibble: 50,400 × 6
    ##     week day_id day    minute activity_counts weekday
    ##    <dbl>  <dbl> <fct>   <dbl>           <dbl> <fct>  
    ##  1     1      1 Friday      1            88.4 weekday
    ##  2     1      1 Friday      2            82.2 weekday
    ##  3     1      1 Friday      3            64.4 weekday
    ##  4     1      1 Friday      4            70.0 weekday
    ##  5     1      1 Friday      5            75.0 weekday
    ##  6     1      1 Friday      6            66.3 weekday
    ##  7     1      1 Friday      7            53.8 weekday
    ##  8     1      1 Friday      8            47.8 weekday
    ##  9     1      1 Friday      9            55.5 weekday
    ## 10     1      1 Friday     10            43.0 weekday
    ## # … with 50,390 more rows

The dataset has 50400 rows and 6 columns with the variables:week,
day\_id, day, minute, activity\_counts, weekday .

#### b) Traditional analyses of accelerometer data focus on the total activity over the day. Using your tidied dataset, aggregate accross minutes to create a total activity variable for each day, and create a table showing these totals. Are any trends apparent?

``` r
accel_eachday = 
accel_weekday %>% 
 group_by(week, day) %>%
  summarize(total_activity = sum(activity_counts)) %>% 
  pivot_wider(
    names_from = day,
    values_from = total_activity
  ) %>% 
  relocate(c("week", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" , "Saturday", "Sunday")) %>% 
  knitr::kable()
```

    ## `summarise()` has grouped output by 'week'. You can override using the `.groups` argument.

``` r
 accel_eachday
```

| week |    Monday |  Tuesday | Wednesday | Thursday |   Friday | Saturday | Sunday |
|-----:|----------:|---------:|----------:|---------:|---------:|---------:|-------:|
|    1 |  78828.07 | 307094.2 |    340115 | 355923.6 | 480542.6 |   376254 | 631105 |
|    2 | 295431.00 | 423245.0 |    440962 | 474048.0 | 568839.0 |   607175 | 422018 |
|    3 | 685910.00 | 381507.0 |    468869 | 371230.0 | 467420.0 |   382928 | 467052 |
|    4 | 409450.00 | 319568.0 |    434460 | 340291.0 | 154049.0 |     1440 | 260617 |
|    5 | 389080.00 | 367824.0 |    445366 | 549658.0 | 620860.0 |     1440 | 138421 |

From the above kabble, I find that the total activity is lower on
weekend than weekday.

#### c) Accelerometer data allows the inspection activity over the course of the day. Make a single-panel plot that shows the 24-hour activity time courses for each day and use color to indicate day of the week. Describe in words any patterns or conclusions you can make based on this graph.

``` r
accel_weekday %>% 
  ggplot(aes(x = minute, y = activity_counts, color = day, group = day_id)) +
  geom_line(alpha = 0.6) + 
  labs(
    title = "24-Hour activity of the day",
    x = "Time",
    y = "Activity Count"
  ) +
## need to scale the x-axis
  scale_x_continuous(
    breaks = c(0, 360, 720, 1080, 1440), 
    labels = c("12am.", "6am.", "12pm.", "6pm.", "11:59pm."),
    limits = c(0, 1440)
  ) 
```

![](p8105_hw3_yz4186_files/figure-gfm/unnamed-chunk-13-1.png)<!-- -->
From the plot I find that patients have 2 peak activity period in a day
at 12 pm. and 11:59 pm. And they keep low level activity at other time.
